---
#
# Ansible managed
#
repository:
  description: Install and configure dryrun on your system.
  homepage: https://robertdebock.nl/
  topics: dryrun, ansible, molecule, tox, playbook, hacktoberfest
